---
apiVersion: v1
kind: Service
metadata:
  name: simplicite
  labels:
    app: simplicite
spec:
  selector:
    app: simplicite
  type: NodePort
  ports:
  - name: http
    port: 8080
  - name: https
    port: 8443
